name = "pho-nha-anna-lucky-wheel"
main = "src/worker.js"
compatibility_date = "2026-09-01"

[[d1_databases]]
binding = "DB"
database_name = "pho-nha-anna"
database_id = "dce30da6-c609-4178-aa13-f7def6b5d255"

[assets]
directory = "./public"

[vars]
RESTAURANT_NAME = "PHỞ NHÀ ANNA"
